export default {
  iterator: () => {},
  size: () => {},
  isEmpty: () => {},
  contains: () => {},
  toArray: () => {},
  add: () => {},
  remove: () => {},
  containsAll: () => {},
  addAll: () => {},
  removeAll: () => {},
  retainAll: () => {},
  clear: () => {},
  toString: () => {},
};
