export default {
  setValue: () => {},
  getValue: () => {},
  getValues: () => {},
  getString: () => {},
  getStream: () => {},
  getBinary: () => {},
  getLong: () => {},
  getDouble: () => {},
  getDecimal: () => {},
  getDate: () => {},
  getBoolean: () => {},
  getNode: () => {},
  getProperty: () => {},
  getLength: () => {},
  getLengths: () => {},
  getDefinition: () => {},
  getType: () => {},
  isMultiple: () => {},
};
