export default {
  getPath: () => {},
  getName: () => {},
  getAncestor: () => {},
  getParent: () => {},
  getDepth: () => {},
  getSession: () => {},
  isNode: () => {},
  isNew: () => {},
  isModified: () => {},
  isSame: () => {},
  accept: () => {},
  save: () => {},
  refresh: () => {},
  remove: () => {},
};
