export default {
  of: () => {},
  ofHours: () => {},
  ofHoursMinutes: () => {},
  ofHoursMinutesSeconds: () => {},
  from: () => {},
  ofTotalSeconds: () => {},
  getTotalSeconds: () => {},
  getId: () => {},
  getRules: () => {},
  isSupported: () => {},
  range: () => {},
  get: () => {},
  getLong: () => {},
  query: () => {},
  adjustInto: () => {},
  compareTo: () => {},
  equals: () => {},
  hashCode: () => {},
  toString: () => {},
};
