export default {
  getMimeType: () => {},
  getExtension: () => {},
  isImageType: () => {},
  isTextType: () => {},
  isXmlType: () => {},
  isVideoType: () => {},
  isCompressedType: () => {},
  isMSWordType: () => {},
  isMSExcelType: () => {},
  isMSPowerpointType: () => {},
  isMSOfficeType: () => {},
  isFontType: () => {},
  isAudioType: () => {},
};
