export default {
  trimToSize: () => {},
  ensureCapacity: () => {},
  size: () => {},
  isEmpty: () => {},
  contains: () => {},
  indexOf: () => {},
  lastIndexOf: () => {},
  clone: () => {},
  toArray: () => {},
  get: () => {},
  set: () => {},
  add: () => {},
  remove: () => {},
  clear: () => {},
  addAll: () => {},
  removeRange: () => {},
  removeAll: () => {},
  retainAll: () => {},
  listIterator: () => {},
  iterator: () => {},
  subList: () => {},
  forEach: () => {},
  spliterator: () => {},
  removeIf: () => {},
  replaceAll: () => {},
  sort: () => {},
};
