export default {
  timeLineOrder: () => {},
  from: () => {},
  getChronology: () => {},
  toLocalDate: () => {},
  toLocalTime: () => {},
  isSupported: () => {},
  with: () => {},
  plus: () => {},
  minus: () => {},
  query: () => {},
  adjustInto: () => {},
  format: () => {},
  atZone: () => {},
  toInstant: () => {},
  toEpochSecond: () => {},
  compareTo: () => {},
  isAfter: () => {},
  isBefore: () => {},
  isEqual: () => {},
  equals: () => {},
  hashCode: () => {},
  toString: () => {},
};
