export default {
  getFileSystem: () => {},
  isAbsolute: () => {},
  getRoot: () => {},
  getFileName: () => {},
  getParent: () => {},
  getNameCount: () => {},
  getName: () => {},
  subpath: () => {},
  startsWith: () => {},
  endsWith: () => {},
  normalize: () => {},
  resolve: () => {},
  resolveSibling: () => {},
  relativize: () => {},
  toUri: () => {},
  toAbsolutePath: () => {},
  toRealPath: () => {},
  toFile: () => {},
  register: () => {},
  iterator: () => {},
  compareTo: () => {},
  equals: () => {},
  hashCode: () => {},
  toString: () => {},
};
