export default {
  getNestedString: () => {},
  getNestedStringEscaped: () => {},
  getNestedInt: () => {},
  getNestedDouble: () => {},
  getNestedBoolean: () => {},
  getNestedNode: () => {},
  getBinary: () => {},
  getNestedBinary: () => {},
  getString: () => {},
  getStringEscaped: () => {},
  getInt: () => {},
  getDouble: () => {},
  getBoolean: () => {},
  getNode: () => {},
  getEnabledNode: () => {},
  getEnabledString: () => {},
  getEnabledStringEscaped: () => {},
  getCalendar: () => {},
  getNestedCalendar: () => {},
  getStrings: () => {},
  getStringsEscaped: () => {},
  getNestedStrings: () => {},
  getNestedStringsEscaped: () => {},
};
