export default {
  getScheme: () => {},
  newFileSystem: () => {},
  getFileSystem: () => {},
  getPath: () => {},
  newInputStream: () => {},
  newOutputStream: () => {},
  newFileChannel: () => {},
  newAsynchronousFileChannel: () => {},
  newByteChannel: () => {},
  newDirectoryStream: () => {},
  createDirectory: () => {},
  createSymbolicLink: () => {},
  createLink: () => {},
  delete: () => {},
  deleteIfExists: () => {},
  readSymbolicLink: () => {},
  copy: () => {},
  move: () => {},
  isSameFile: () => {},
  isHidden: () => {},
  getFileStore: () => {},
  checkAccess: () => {},
  getFileAttributeView: () => {},
  readAttributes: () => {},
  setAttribute: () => {},
};
