export default {
  size: () => {},
  isEmpty: () => {},
  containsKey: () => {},
  containsValue: () => {},
  get: () => {},
  put: () => {},
  remove: () => {},
  putAll: () => {},
  clear: () => {},
  keySet: () => {},
  values: () => {},
  entrySet: () => {},
  equals: () => {},
  hashCode: () => {},
  getOrDefault: () => {},
  forEach: () => {},
  replaceAll: () => {},
  putIfAbsent: () => {},
  replace: () => {},
  computeIfAbsent: () => {},
  computeIfPresent: () => {},
  compute: () => {},
  merge: () => {},
};
