export default {
  getContacts: () => {},
  isContact: () => {},
  addContact: () => {},
  removeContact: () => {},
  getCollaborationGroups: () => {},
  isAdminOf: () => {},
  isMemberOf: () => {},
  leaveGroup: () => {},
  joinGroup: () => {},
  followGroup: () => {},
  getFollowedGroups: () => {},
  isFollowing: () => {},
  unfollowGroup: () => {},
  muteGroup: () => {},
  unmuteGroup: () => {},
  isGroupMuted: () => {},
  muteNotifications: () => {},
  unmuteNotifications: () => {},
  isNotificationsMuted: () => {},
  getProfileImage: () => {},
  getProfileImagesFolder: () => {},
  setProfileImage: () => {},
  setHidden: () => {},
  setDisabled: () => {},
  isDisabled: () => {},
  getUserIdentity: () => {},
};
