export default {
  clone: () => {},
  getYear: () => {},
  setYear: () => {},
  getMonth: () => {},
  setMonth: () => {},
  getDate: () => {},
  setDate: () => {},
  getDay: () => {},
  getHours: () => {},
  setHours: () => {},
  getMinutes: () => {},
  setMinutes: () => {},
  getSeconds: () => {},
  setSeconds: () => {},
  getTime: () => {},
  setTime: () => {},
  before: () => {},
  after: () => {},
  equals: () => {},
  compareTo: () => {},
  hashCode: () => {},
  toString: () => {},
  toLocaleString: () => {},
  toGMTString: () => {},
  getTimezoneOffset: () => {},
  toInstant: () => {},
};
