export default {
  addQueryField: () => {},
  clearQueryFields: () => {},
  setTieBreaker: () => {},
  setUserFields: () => {},
  setMinimumShouldMatch: () => {},
  addPhraseField: () => {},
  clearPhraseFields: () => {},
  setBoostQuery: () => {},
  addAdditiveBoostFunction: () => {},
  clearAdditiveBoostFunctions: () => {},
  addMultiplicativeBoostFunction: () => {},
  clearMultiplicativeBoostFunctions: () => {},
  build: () => {},
};
