export default {
  of: () => {},
  getInstant: () => {},
  toEpochSecond: () => {},
  getDateTimeBefore: () => {},
  getDateTimeAfter: () => {},
  getOffsetBefore: () => {},
  getOffsetAfter: () => {},
  getDuration: () => {},
  isGap: () => {},
  isOverlap: () => {},
  isValidOffset: () => {},
  compareTo: () => {},
  equals: () => {},
  hashCode: () => {},
  toString: () => {},
};
