export default {
  getVersionableUUID: () => {},
  getVersionableIdentifier: () => {},
  getRootVersion: () => {},
  getAllLinearVersions: () => {},
  getAllVersions: () => {},
  getAllLinearFrozenNodes: () => {},
  getAllFrozenNodes: () => {},
  getVersion: () => {},
  getVersionByLabel: () => {},
  addVersionLabel: () => {},
  removeVersionLabel: () => {},
  hasVersionLabel: () => {},
  getVersionLabels: () => {},
  removeVersion: () => {},
};
