export default {
  size: () => {},
  isEmpty: () => {},
  contains: () => {},
  iterator: () => {},
  toArray: () => {},
  add: () => {},
  remove: () => {},
  containsAll: () => {},
  addAll: () => {},
  retainAll: () => {},
  removeAll: () => {},
  clear: () => {},
  equals: () => {},
  hashCode: () => {},
  spliterator: () => {},
};
