export default {
  set2DigitYearStart: () => {},
  get2DigitYearStart: () => {},
  format: () => {},
  formatToCharacterIterator: () => {},
  parse: () => {},
  toPattern: () => {},
  toLocalizedPattern: () => {},
  applyPattern: () => {},
  applyLocalizedPattern: () => {},
  getDateFormatSymbols: () => {},
  setDateFormatSymbols: () => {},
  clone: () => {},
  hashCode: () => {},
  equals: () => {},
};
