export default {
  timeLineOrder: () => {},
  from: () => {},
  getChronology: () => {},
  getEra: () => {},
  isLeapYear: () => {},
  lengthOfMonth: () => {},
  lengthOfYear: () => {},
  isSupported: () => {},
  with: () => {},
  plus: () => {},
  minus: () => {},
  query: () => {},
  adjustInto: () => {},
  until: () => {},
  format: () => {},
  atTime: () => {},
  toEpochDay: () => {},
  compareTo: () => {},
  isAfter: () => {},
  isBefore: () => {},
  isEqual: () => {},
  equals: () => {},
  hashCode: () => {},
  toString: () => {},
};
