export default {
  ofPattern: () => {},
  ofLocalizedDate: () => {},
  ofLocalizedTime: () => {},
  ofLocalizedDateTime: () => {},
  parsedExcessDays: () => {},
  parsedLeapSecond: () => {},
  getLocale: () => {},
  withLocale: () => {},
  getDecimalStyle: () => {},
  withDecimalStyle: () => {},
  getChronology: () => {},
  withChronology: () => {},
  getZone: () => {},
  withZone: () => {},
  getResolverStyle: () => {},
  withResolverStyle: () => {},
  getResolverFields: () => {},
  withResolverFields: () => {},
  format: () => {},
  formatTo: () => {},
  parse: () => {},
  parseBest: () => {},
  parseUnresolved: () => {},
  toFormat: () => {},
  toString: () => {},
};
