export default {
  getHits: () => {},
  iterator: () => {},
  getExactCount: () => {},
  hasHits: () => {},
  getApproximateCount: () => {},
  getEffectiveCount: () => {},
  getQuery: () => {},
  getDisplayQuery: () => {},
  getStatus: () => {},
  getStatusMessage: () => {},
  getFacetFields: () => {},
  getSuggestions: () => {},
  getCustomSorts: () => {},
  getSearchHighlighter: () => {},
  getDateFormatter: () => {},
};
