export default {
  setLocale: () => {},
  setUseSmallIcons: () => {},
  clearUseSmallIcons: () => {},
  forceUseSmallIcons: () => {},
  setUseDescription: () => {},
  clearUseDescription: () => {},
  forceUseDescription: () => {},
  loadDefaultIconByContentType: () => {},
  loadDefaultIconByURI: () => {},
  loadDefaultIconByFileExtension: () => {},
  isDefaultIconLoaded: () => {},
  clearDefaultIcon: () => {},
  loadIconByContentType: () => {},
  loadIconByURI: () => {},
  loadIconByFileExtension: () => {},
  isIconLoaded: () => {},
  clearIcon: () => {},
  setFontClass: () => {},
  clearFontClass: () => {},
  render: () => {},
};
