export default {
  isMulticastAddress: () => {},
  isAnyLocalAddress: () => {},
  isLoopbackAddress: () => {},
  isLinkLocalAddress: () => {},
  isSiteLocalAddress: () => {},
  isMCGlobal: () => {},
  isMCNodeLocal: () => {},
  isMCLinkLocal: () => {},
  isMCSiteLocal: () => {},
  isMCOrgLocal: () => {},
  isReachable: () => {},
  getHostName: () => {},
  getCanonicalHostName: () => {},
  getAddress: () => {},
  getHostAddress: () => {},
  hashCode: () => {},
  equals: () => {},
  toString: () => {},
};
