export default {
  flatten() {},
  getFalse() {},
  getHumanPresentableSize() {},
  getList() {},
  getNonBlank() {},
  getNonNull() {},
  getNull() {},
  getTrue() {},
  isBlank() {},
  isEmpty() {},
  isFalse() {},
  isNotBlank() {},
  isNotEmpty() {},
  isTrue() {},
  joinArray() {},
  joinCollection() {},
  messageFormat() {},
  stringToDouble() {},
  stringToFloat() {},
  stringToInt() {},
  stringToLong() {},
  swallow() {},
  trimToEmpty() {},
  trimToNull() {},
};
