export default {
  isString: () => {},
  isBoolean: () => {},
  isInteger: () => {},
  isLong: () => {},
  isDouble: () => {},
  isFloat: () => {},
  isNumber: () => {},
  isNode: () => {},
  isProperty: () => {},
  isDate: () => {},
  isCalendar: () => {},
  isList: () => {},
  isMap: () => {},
  isSet: () => {},
  isCollection: () => {},
  isIterator: () => {},
  isIterable: () => {},
  isSerializable: () => {},
  isComparator: () => {},
  isComparable: () => {},
  isException: () => {},
  isThrowable: () => {},
};
