export default {
  escapeXML: () => {},
  unEscapeXML: () => {},
  unEscapeHTML4: () => {},
  encodeURL: () => {},
  decodeURL: () => {},
  br: () => {},
  getBaseSubstitute: () => {},
  escapeJcrName: () => {},
  unEscapeJcrName: () => {},
  base64encode: () => {},
  base64encodeToString: () => {},
  base64decode: () => {},
  base64decodeToBytes: () => {},
  escapeIdentifier: () => {},
  unEscapeIdentifier: () => {},
};
