export default {
  fieldContains: () => {},
  fieldEquals: () => {},
  fieldEqualsIgnoreCase: () => {},
  fieldMatches: () => {},
  getNode: () => {},
  getField: () => {},
  getFieldEscaped: () => {},
  getFields: () => {},
  getFieldsEscaped: () => {},
  getFieldsTruncated: () => {},
  getBooleanField: () => {},
  getBooleanFields: () => {},
  getDateField: () => {},
  getDateFields: () => {},
  getFloatField: () => {},
  getFloatFields: () => {},
  getLongField: () => {},
  getLongFields: () => {},
  getHighlightedField: () => {},
  getHighlightedFields: () => {},
  getFieldTruncated: () => {},
  getFieldNames: () => {},
  getScore: () => {},
  isElevated: () => {},
  getType: () => {},
  getClickTrackingCallback: () => {},
};
