export default {
  from: () => {},
  ofLocale: () => {},
  of: () => {},
  getAvailableChronologies: () => {},
  getId: () => {},
  getCalendarType: () => {},
  date: () => {},
  dateYearDay: () => {},
  dateEpochDay: () => {},
  dateNow: () => {},
  localDateTime: () => {},
  zonedDateTime: () => {},
  isLeapYear: () => {},
  prolepticYear: () => {},
  eraOf: () => {},
  eras: () => {},
  range: () => {},
  getDisplayName: () => {},
  resolveDate: () => {},
  period: () => {},
  compareTo: () => {},
  equals: () => {},
  hashCode: () => {},
  toString: () => {},
};
