export default {
  systemUTC: () => {},
  systemDefaultZone: () => {},
  system: () => {},
  tickSeconds: () => {},
  tickMinutes: () => {},
  tick: () => {},
  fixed: () => {},
  offset: () => {},
  getZone: () => {},
  withZone: () => {},
  millis: () => {},
  instant: () => {},
  equals: () => {},
  hashCode: () => {},
};
