export default {
  setProperty: () => {},
  getNode: () => {},
  getNodes: () => {},
  getProperty: () => {},
  getProperties: () => {},
  getUUID: () => {},
  getIdentifier: () => {},
  hasNode: () => {},
  hasProperty: () => {},
  hasNodes: () => {},
  hasProperties: () => {},
  getPrimaryNodeType: () => {},
  getMixinNodeTypes: () => {},
  isNodeType: () => {},
};
