export default {
  getOffset: () => {},
  setRawOffset: () => {},
  getRawOffset: () => {},
  getID: () => {},
  setID: () => {},
  getDisplayName: () => {},
  getDSTSavings: () => {},
  useDaylightTime: () => {},
  observesDaylightTime: () => {},
  inDaylightTime: () => {},
  getTimeZone: () => {},
  toZoneId: () => {},
  getAvailableIDs: () => {},
  getDefault: () => {},
  setDefault: () => {},
  hasSameRules: () => {},
  clone: () => {},
};
