export default {
  of: () => {},
  isFixed: () => {},
  getMinimum: () => {},
  getLargestMinimum: () => {},
  getSmallestMaximum: () => {},
  getMaximum: () => {},
  isIntValue: () => {},
  isValidValue: () => {},
  isValidIntValue: () => {},
  checkValidValue: () => {},
  checkValidIntValue: () => {},
  equals: () => {},
  hashCode: () => {},
  toString: () => {},
};
