/**
 * This file is auto generated. Do not modify it manually.
 */
export default {
  createQuery: () => {},
  selector: () => {},
  join: () => {},
  equiJoinCondition: () => {},
  sameNodeJoinCondition: () => {},
  childNodeJoinCondition: () => {},
  descendantNodeJoinCondition: () => {},
  and: () => {},
  or: () => {},
  not: () => {},
  comparison: () => {},
  propertyExistence: () => {},
  fullTextSearch: () => {},
  sameNode: () => {},
  childNode: () => {},
  descendantNode: () => {},
  propertyValue: () => {},
  length: () => {},
  nodeName: () => {},
  nodeLocalName: () => {},
  fullTextSearchScore: () => {},
  lowerCase: () => {},
  upperCase: () => {},
  bindVariable: () => {},
  literal: () => {},
  ascending: () => {},
  descending: () => {},
  column: () => {},
};
