export default {
  getAdmins: () => {},
  isAdmin: () => {},
  addAdmin: () => {},
  getMembers: () => {},
  isMember: () => {},
  addMember: () => {},
  removeMember: () => {},
  getFollowers: () => {},
  isFollower: () => {},
  renameGroup: () => {},
  getGroupType: () => {},
  setGroupType: () => {},
  getGroupState: () => {},
  setGroupState: () => {},
  getGroupDescription: () => {},
  setGroupDescription: () => {},
  getProfileImagesFolder: () => {},
  getProfileImage: () => {},
  setProfileImage: () => {},
  setLocale: () => {},
  getCollaborationGroup: () => {},
};
