export default {
  getPROPERTY_VISIBLE_IN_MENUS: () => {},
  getPROPERTY_CREATION_DATE: () => {},
  getPROPERTY_CREATED_BY: () => {},
  getPROPERTY_LAST_MODIFIED_DATE: () => {},
  getPROPERTY_LAST_MODIFIED_BY: () => {},
  getPROPERTY_LAST_PUBLISHED_BY: () => {},
  getPROPERTY_LAST_PUBLISH_DATE: () => {},
  getPROPERTY_PUBLISHED_BY: () => {},
  getPROPERTY_PUBLISH_DATE: () => {},
  getPROPERTY_LAST_UNPUBLISHED_BY: () => {},
  getPROPERTY_LAST_UNPUBLISH_DATE: () => {},
};
