export default {
  getEras: () => {},
  setEras: () => {},
  getMonths: () => {},
  setMonths: () => {},
  getShortMonths: () => {},
  setShortMonths: () => {},
  getWeekdays: () => {},
  setWeekdays: () => {},
  getShortWeekdays: () => {},
  setShortWeekdays: () => {},
  getAmPmStrings: () => {},
  setAmPmStrings: () => {},
  getZoneStrings: () => {},
  setZoneStrings: () => {},
  getLocalPatternChars: () => {},
  setLocalPatternChars: () => {},
  clone: () => {},
  hashCode: () => {},
  equals: () => {},
};
