export default {
  addFirst: () => {},
  addLast: () => {},
  offerFirst: () => {},
  offerLast: () => {},
  removeFirst: () => {},
  removeLast: () => {},
  pollFirst: () => {},
  pollLast: () => {},
  getFirst: () => {},
  getLast: () => {},
  peekFirst: () => {},
  peekLast: () => {},
  removeFirstOccurrence: () => {},
  removeLastOccurrence: () => {},
  add: () => {},
  offer: () => {},
  remove: () => {},
  poll: () => {},
  element: () => {},
  peek: () => {},
  push: () => {},
  pop: () => {},
  contains: () => {},
  size: () => {},
  iterator: () => {},
  descendingIterator: () => {},
};
