export default {
  getAvailableLocales: () => {},
  ofDefaultLocale: () => {},
  of: () => {},
  getZeroDigit: () => {},
  withZeroDigit: () => {},
  getPositiveSign: () => {},
  withPositiveSign: () => {},
  getNegativeSign: () => {},
  withNegativeSign: () => {},
  getDecimalSeparator: () => {},
  withDecimalSeparator: () => {},
  equals: () => {},
  hashCode: () => {},
  toString: () => {},
};
