export default {
  format: () => {},
  parseObject: () => {},
  parse: () => {},
  isParseIntegerOnly: () => {},
  setParseIntegerOnly: () => {},
  hashCode: () => {},
  equals: () => {},
  clone: () => {},
  isGroupingUsed: () => {},
  setGroupingUsed: () => {},
  getMaximumIntegerDigits: () => {},
  setMaximumIntegerDigits: () => {},
  getMinimumIntegerDigits: () => {},
  setMinimumIntegerDigits: () => {},
  getMaximumFractionDigits: () => {},
  setMaximumFractionDigits: () => {},
  getMinimumFractionDigits: () => {},
  setMinimumFractionDigits: () => {},
  getCurrency: () => {},
  setCurrency: () => {},
  getRoundingMode: () => {},
  setRoundingMode: () => {},
};
