export default {
  lowerEntry: () => {},
  lowerKey: () => {},
  floorEntry: () => {},
  floorKey: () => {},
  ceilingEntry: () => {},
  ceilingKey: () => {},
  higherEntry: () => {},
  higherKey: () => {},
  firstEntry: () => {},
  lastEntry: () => {},
  pollFirstEntry: () => {},
  pollLastEntry: () => {},
  descendingMap: () => {},
  navigableKeySet: () => {},
  descendingKeySet: () => {},
  subMap: () => {},
  headMap: () => {},
  tailMap: () => {},
};
