export default {
  NOT_PUBLISHED: "NOT_PUBLISHED",
  PUBLISHED: "PUBLISHED",
  WORKFLOW_STARTED: "WORKFLOW_STARTED",
  SCHEDULED_PUBLISH: "SCHEDULED_PUBLISH",
  SCHEDULED_UNPUBLISH: "SCHEDULED_UNPUBLISH",
  SCHEDULED_PUBLISH_BY_PUBLISHING_PROJECT:
    "SCHEDULED_PUBLISH_BY_PUBLISHING_PROJECT",
  BELONGS_TO_PUBLISHING_PROJECT: "BELONGS_TO_PUBLISHING_PROJECT",
  LOCKED: "LOCKED",
};
