export default {
  of: () => {},
  isFixedOffset: () => {},
  getOffset: () => {},
  getValidOffsets: () => {},
  getTransition: () => {},
  getStandardOffset: () => {},
  getDaylightSavings: () => {},
  isDaylightSavings: () => {},
  isValidOffset: () => {},
  nextTransition: () => {},
  previousTransition: () => {},
  getTransitions: () => {},
  getTransitionRules: () => {},
  equals: () => {},
  hashCode: () => {},
  toString: () => {},
};
