export default {
  checkin: () => {},
  checkout: () => {},
  checkpoint: () => {},
  isCheckedOut: () => {},
  getVersionHistory: () => {},
  getBaseVersion: () => {},
  restore: () => {},
  restoreByLabel: () => {},
  merge: () => {},
  doneMerge: () => {},
  cancelMerge: () => {},
  createConfiguration: () => {},
  setActivity: () => {},
  getActivity: () => {},
  createActivity: () => {},
  removeActivity: () => {},
};
