export default {
  sort: () => {},
  binarySearch: () => {},
  equals: () => {},
  fill: () => {},
  copyOf: () => {},
  copyOfRange: () => {},
  asList: () => {},
  hashCode: () => {},
  deepHashCode: () => {},
  deepEquals: () => {},
  toString: () => {},
  deepToString: () => {},
  parallelSort: () => {},
  parallelPrefix: () => {},
  setAll: () => {},
  parallelSetAll: () => {},
  spliterator: () => {},
  stream: () => {},
};
