export default {
  getId: () => {},
  getCalendarType: () => {},
  date: () => {},
  dateYearDay: () => {},
  dateEpochDay: () => {},
  localDateTime: () => {},
  zonedDateTime: () => {},
  dateNow: () => {},
  isLeapYear: () => {},
  prolepticYear: () => {},
  eraOf: () => {},
  eras: () => {},
  resolveDate: () => {},
  range: () => {},
  period: () => {},
};
