export default {
  addContact() {},
  followGroup() {},
  getCollaborationGroups() {},
  getContacts() {},
  getFollowedGroups() {},
  getProfileImage() {},
  getProfileImagesFolder() {},
  getUserIdentity() {},
  isAdminOf() {},
  isContact() {},
  isDisabled() {},
  isFollowing() {},
  isMemberOf() {},
  joinGroup() {},
  leaveGroup() {},
  removeContact() {},
  setDisabled() {},
  setHidden() {},
  setProfileImage() {},
  unfollowGroup() {},
};
