export default {
  between: () => {},
  get: () => {},
  getUnits: () => {},
  getChronology: () => {},
  isZero: () => {},
  isNegative: () => {},
  plus: () => {},
  minus: () => {},
  multipliedBy: () => {},
  negated: () => {},
  normalized: () => {},
  addTo: () => {},
  subtractFrom: () => {},
  equals: () => {},
  hashCode: () => {},
  toString: () => {},
};
