export default {
  format: () => {},
  parse: () => {},
  parseObject: () => {},
  setCalendar: () => {},
  getCalendar: () => {},
  setNumberFormat: () => {},
  getNumberFormat: () => {},
  setTimeZone: () => {},
  getTimeZone: () => {},
  setLenient: () => {},
  isLenient: () => {},
  hashCode: () => {},
  equals: () => {},
  clone: () => {},
};
