export default {
  format: () => {},
  parse: () => {},
  parseObject: () => {},
  getTimeInstance: () => {},
  getDateInstance: () => {},
  getDateTimeInstance: () => {},
  getInstance: () => {},
  getAvailableLocales: () => {},
  setCalendar: () => {},
  getCalendar: () => {},
  setNumberFormat: () => {},
  getNumberFormat: () => {},
  setTimeZone: () => {},
  getTimeZone: () => {},
  setLenient: () => {},
  isLenient: () => {},
  hashCode: () => {},
  equals: () => {},
  clone: () => {},
};
