export default {
  size: () => {},
  isEmpty: () => {},
  contains: () => {},
  iterator: () => {},
  toArray: () => {},
  add: () => {},
  remove: () => {},
  containsAll: () => {},
  addAll: () => {},
  removeAll: () => {},
  retainAll: () => {},
  replaceAll: () => {},
  sort: () => {},
  clear: () => {},
  equals: () => {},
  hashCode: () => {},
  get: () => {},
  set: () => {},
  indexOf: () => {},
  lastIndexOf: () => {},
  listIterator: () => {},
  subList: () => {},
  spliterator: () => {},
};
