export default {
  getRepository: () => {},
  getUserID: () => {},
  getAttributeNames: () => {},
  getAttribute: () => {},
  getWorkspace: () => {},
  getRootNode: () => {},
  impersonate: () => {},
  getNodeByIdentifier: () => {},
  getItem: () => {},
  getNode: () => {},
  getProperty: () => {},
  itemExists: () => {},
  nodeExists: () => {},
  propertyExists: () => {},
  getValueFactory: () => {},
  getNamespacePrefixes: () => {},
  getNamespaceURI: () => {},
  getNamespacePrefix: () => {},
  logout: () => {},
  isLive: () => {},
};
