export default {
  compare: () => {},
  equals: () => {},
  reversed: () => {},
  thenComparing: () => {},
  thenComparingInt: () => {},
  thenComparingLong: () => {},
  thenComparingDouble: () => {},
  reverseOrder: () => {},
  naturalOrder: () => {},
  nullsFirst: () => {},
  nullsLast: () => {},
  comparing: () => {},
  comparingInt: () => {},
  comparingLong: () => {},
  comparingDouble: () => {},
};
