export default {
  name: () => {},
  aliases: () => {},
  displayName: () => {},
  isRegistered: () => {},
  contains: () => {},
  newDecoder: () => {},
  newEncoder: () => {},
  canEncode: () => {},
  decode: () => {},
  encode: () => {},
  compareTo: () => {},
  hashCode: () => {},
  equals: () => {},
  toString: () => {},
};
