export default {
  getQuery: () => {},
  getPath: () => {},
  getUserInfo: () => {},
  getAuthority: () => {},
  getPort: () => {},
  getDefaultPort: () => {},
  getProtocol: () => {},
  getHost: () => {},
  getFile: () => {},
  getRef: () => {},
  equals: () => {},
  hashCode: () => {},
  sameFile: () => {},
  toString: () => {},
  toExternalForm: () => {},
  toURI: () => {},
  openConnection: () => {},
  openStream: () => {},
  getContent: () => {},
};
