export default {
  getName: () => {},
  getInetAddresses: () => {},
  getInterfaceAddresses: () => {},
  getSubInterfaces: () => {},
  getParent: () => {},
  getIndex: () => {},
  getDisplayName: () => {},
  isUp: () => {},
  isLoopback: () => {},
  isPointToPoint: () => {},
  supportsMulticast: () => {},
  getHardwareAddress: () => {},
  getMTU: () => {},
  isVirtual: () => {},
  equals: () => {},
  hashCode: () => {},
  toString: () => {},
};
