export default {
  getSession: () => {},
  getName: () => {},
  copy: () => {},
  clone: () => {},
  move: () => {},
  restore: () => {},
  getLockManager: () => {},
  getQueryManager: () => {},
  getNamespaceRegistry: () => {},
  getNodeTypeManager: () => {},
  getObservationManager: () => {},
  getVersionManager: () => {},
  getAccessibleWorkspaceNames: () => {},
  getImportContentHandler: () => {},
  importXML: () => {},
  createWorkspace: () => {},
  deleteWorkspace: () => {},
};
