export default {
  PROPERTY_CREATED_BY: '',
  PROPERTY_CREATION_DATE: '',
  PROPERTY_LAST_MODIFIED_BY: '',
  PROPERTY_LAST_MODIFIED_DATE: '',
  PROPERTY_LAST_PUBLISH_DATE: '',
  PROPERTY_LAST_PUBLISHED_BY: '',
  PROPERTY_LOCALE: '',
  PROPERTY_PUBLISH_DATE: '',
  PROPERTY_PUBLISHED_BY: '',
  PROPERTY_ROBOTS_INDEX: '',
  PROPERTY_SHORTID: '',
  PROPERTY_VISIBLE_IN_MENUS: '',

  createArticle: () => ({}),
  renameArticle: () => {},
  updateArticle: () => {},
};
