export default {
  getNecessarySiteCookies: () => {},
  getNecessarySiteCookiesTitle: () => {},
  getNecessarySiteCookiesDescription: () => {},
  getAnalyticsSiteCookies: () => {},
  getAnalyticsSiteCookiesTitle: () => {},
  getAnalyticsSiteCookiesDescription: () => {},
  getMarketingSiteCookies: () => {},
  getMarketingSiteCookiesTitle: () => {},
  getMarketingSiteCookiesDescription: () => {},
  getFunctionalSiteCookies: () => {},
  getFunctionalSiteCookiesTitle: () => {},
  getFunctionalSiteCookiesDescription: () => {},
  getCustomSiteCookies: () => {},
  getCustomSiteCookiesTitle: () => {},
  getCustomSiteCookiesDescription: () => {},
  resolveSiteCookieByIdentifier: () => {},
  checkUserConsent: () => {},
  hasPendingUserConsents: () => {},
  hasUserConsentCookie: () => {},
  getUserConsentCookieName: () => {},
  createUserConsentCookieValue: () => {},
  getUserConsents: () => {},
};
