export default {
  add: () => {},
  get: () => {},
  set: () => {},
  remove: () => {},
  indexOf: () => {},
  lastIndexOf: () => {},
  clear: () => {},
  addAll: () => {},
  iterator: () => {},
  listIterator: () => {},
  subList: () => {},
  equals: () => {},
  hashCode: () => {},
  removeRange: () => {},
};
