export default {
  getValue: () => {},
  getValues: () => {},
  getString: () => {},
  getLong: () => {},
  getDouble: () => {},
  getDecimal: () => {},
  getDate: () => {},
  getBoolean: () => {},
  getNode: () => {},
  getProperty: () => {},
  getDefinition: () => {},
  getType: () => {},
  isMultiple: () => {},
};
