export default {
  getNecessarySiteCookies() {},
  getNecessarySiteCookiesTitle() {},
  getNecessarySiteCookiesDescription() {},
  getAnalyticsSiteCookies() {},
  getAnalyticsSiteCookiesTitle() {},
  getAnalyticsSiteCookiesDescription() {},
  getMarketingSiteCookies() {},
  getMarketingSiteCookiesTitle() {},
  getMarketingSiteCookiesDescription() {},
  getCustomSiteCookies() {},
  getCustomSiteCookiesTitle() {},
  getCustomSiteCookiesDescription() {},
  resolveSiteCookieByIdentifier() {},
  checkUserConsent() {},
  hasPendingUserConsents() {},
  hasUserConsentCookie() {},
  getUserConsentCookieName() {},
  createUserConsentCookieValue() {},
  getUserConsents() {},
};
